apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: bun-elysia-paseto-api-pdb
  namespace: default
  labels:
    app: bun-elysia-paseto-api
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: bun-elysia-paseto-api
